### ISSUE TITLE
`cross` function call bad in `mesh.surface()`

### ISSUE THREAD

**Issue by coderforlife** [jimy-byerley/pymadcad#50]
Isn't this supposed to be `cross(a-b, a-c)` instead of `cross(a-b, a,c)`?

https://github.com/jimy-byerley/pymadcad/blob/029a859af9b97792c3e033b0d0a87c8525531dae/madcad/mesh/mesh.py#L395

**Comment by jimy-byerley** [comment]
That's right again, I apologize ... This is fixed in 978491aaf808909045f15d4d3bbe306bc260076e
I will make a release soon
