### ISSUE TITLE
`mesh.volume()` returns a vec3 instead of a number

### ISSUE THREAD

**Issue by coderforlife** [jimy-byerley/pymadcad#51]
This should probably be `s = 0.0`

https://github.com/jimy-byerley/pymadcad/blob/029a859af9b97792c3e033b0d0a87c8525531dae/madcad/mesh/mesh.py#L401

The only thing added to it is a determinant, which is a scalar, not a vec3. Also, this function could just use a `return sum(...)`.

**Comment by jimy-byerley** [comment]
That's right, I don't know how I could have wrote that ... This is fixed in 978491aaf808909045f15d4d3bbe306bc260076e
I will make a release soon

**Comment by jimy-byerley** [comment]
this has been released in v0.14 ;)
