### ISSUE TITLE
missing .gitignore, 

### ISSUE THREAD

**Issue by GlennWSo** [jimy-byerley/pymadcad#57]
Hi,

As developer and someone who wants to contribute to this project I am missing a ".gitignore" file.

Without the  .gitignore file i do not know which files should be  _excluded_ included in future pull requests.

**Comment by jimy-byerley** [comment]
Hum ... isn't that simpler to only include the source files you created ?

**Comment by GlennWSo** [comment]
Tools like "git status" has greatly improved signal to noise ratio with a .gitignore file. It also clearly communicates to contributors so they know what u don't want.

Merry Christmas btw 🌲

**Comment by jimy-byerley** [comment]
That's right ... what afraid me is that there will always be new IDEs or tools creating their own temporary files with always different names. And the gitignore is always bigger and bigger. I use gitignore files without comiting them, so they are specific to the computer and tools I'm using them on.
Well I suppose it's not that important ;)

Merry Christmas for you too :christmas_tree:
