### ISSUE TITLE
Wrong error message in mesh.conversions.wire

### ISSUE THREAD

**Issue by WizardUli** [jimy-byerley/pymadcad#77]
https://github.com/jimy-byerley/pymadcad/blob/22437d1edc9e0c13df183ca046f79fcf4e0f958f/madcad/mesh/conversions.py#L80
should have been `'wire take at least one argument'`.

**Comment by jimy-byerley** [comment]
sure

**Comment by jimy-byerley** [comment]
this is fixed in 25da3b9aacfc4958ea1c677d0606ae839f268c27
