### ISSUE TITLE
How to add color to each vertex?

### ISSUE THREAD

**Issue by JeffreyWardman** [jimy-byerley/pymadcad#97]
I want to be able to store the RGB/RGBA information in the mesh so I can either display it via `madcad.show()` or via another library. I want to ensure that the RGB/RGBA information is extended to other points, e.g. after `madcad.thicken(mesh)`.

Is this possible? If stored as an `option`, would it be manipulated as well?

**Comment by jimy-byerley** [comment]
Hello, sorry for the answering delay

My answer will be disappointing: there is no way to keep such per-vertex information in madcad meshes, `Mesh.options` is just data associated to the mesh but its content is not processed by mesh manipulation functions
If you have to keep such information along with the meshes, you will have to do it by hand ... :-/
